### ISSUE TITLE
[Chores] Use new version of inyono/changelog

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/serlo.org-database-layer#281]
in the new changelog.ts there is no need to set `name`, but just `tagName`.

**Comment by inyono** [comment]
FYI: `name` is just an optional "prettier" name (e.g. in our case to get rid of the `v` prefix).

**Comment by hugotiburtino** [comment]
Thanks for your feedback.
I didn't know that. In version 0.4 the changelog package works good. With that is this issue resolved.
But just to note: after upgrading it to 0.5.2 I get the error 
```console
/home/hugo/ws/serlo/serlo.org-database-layer/node_modules/ts-node/dist/index.js:842
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/hugo/ws/serlo/serlo.org-database-layer/node_modules/@inyono/changelog/dist/index.js from /home/hugo/ws/serlo/serlo.org-database-layer/scripts/changelog.ts not supported.
Instead change the require of index.js in /home/hugo/ws/serlo/serlo.org-database-layer/scripts/changelog.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (/home/hugo/ws/serlo/serlo.org-database-layer/node_modules/ts-node/dist/index.js:842:20)
    at Object.<anonymous> (/home/hugo/ws/serlo/serlo.org-database-layer/scripts/changelog.ts:26:21)
    at Module.m._compile (/home/hugo/ws/serlo/serlo.org-database-layer/node_modules/ts-node/dist/index.js:848:29)
    at Object.require.extensions.<computed> [as .ts] (/home/hugo/ws/serlo/serlo.org-database-layer/node_modules/ts-node/dist/index.js:850:16)
    at phase4 (/home/hugo/ws/serlo/serlo.org-database-layer/node_modules/ts-node/dist/bin.js:414:16)
    at bootstrap (/home/hugo/ws/serlo/serlo.org-database-layer/node_modules/ts-node/dist/bin.js:49:12)
    at main (/home/hugo/ws/serlo/serlo.org-database-layer/node_modules/ts-node/dist/bin.js:32:12)
    at Object.<anonymous> (/home/hugo/ws/serlo/serlo.org-database-layer/node_modules/ts-node/dist/bin.js:526:5) {
  code: 'ERR_REQUIRE_ESM'
}
```
